# Generated by Django 5.2.3 on 2025-07-31 11:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('idass', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ass', models.CharField(max_length=50)),
                ('code_ass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('idcarb', models.AutoField(primary_key=True, serialize=False)),
                ('type_carb', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carosserie',
            fields=[
                ('idcar', models.AutoField(primary_key=True, serialize=False)),
                ('code_car', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idcat', models.AutoField(primary_key=True, serialize=False)),
                ('code_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Centrevisite',
            fields=[
                ('idcentre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_centre', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('idcont', models.AutoField(primary_key=True, serialize=False)),
                ('date_visite', models.DateField()),
                ('date_valid', models.DateField()),
                ('pv_num', models.CharField(max_length=20)),
                ('aptitude', models.CharField(max_length=20)),
                ('date_delivrance_c', models.DateField()),
                ('frequence_mois', models.IntegerField(default=12)),
                ('est_valide', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur'), ('gestionnaire', 'Gestionnaire'), ('mecanicien', 'Mécanicien')], default='user', max_length=20)),
                ('keycloak_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idmar', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mar', models.CharField(max_length=70)),
                ('lettre', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('idpiece', models.AutoField(primary_key=True, serialize=False)),
                ('nom_piece', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantite_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reparation',
            fields=[
                ('idrep', models.AutoField(primary_key=True, serialize=False)),
                ('date_reparation', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type_repar', models.CharField(max_length=100)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('garge', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('idstation', models.AutoField(primary_key=True, serialize=False)),
                ('nom_station', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('idag', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ag', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('idass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assurance')),
            ],
        ),
        migrations.CreateModel(
            name='Carteviolette',
            fields=[
                ('idcarte', models.AutoField(primary_key=True, serialize=False)),
                ('date_delivrance', models.DateField()),
                ('num_carte', models.CharField(max_length=20)),
                ('idcont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controle')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('idmod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mod', models.CharField(max_length=70)),
                ('idmar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('idoper', models.AutoField(primary_key=True, serialize=False)),
                ('nom_oper', models.CharField(max_length=100)),
                ('idcentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centrevisite')),
            ],
        ),
        migrations.AddField(
            model_name='controle',
            name='idoper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operateur'),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('num_police', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_assurance', models.CharField(choices=[('obligatoire', 'Obligatoire'), ('tiers', 'Responsabilité civile'), ('tous_risques', 'Tous risques')], max_length=20)),
                ('date_delivrance', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut_pol', models.CharField(max_length=20)),
                ('idag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('idcot', models.AutoField(primary_key=True, serialize=False)),
                ('mtt_cot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_cp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_de', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_ca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_div', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cot', models.DateField()),
                ('date_debut_couverture', models.DateField()),
                ('date_fin_couverture', models.DateField()),
                ('statut_paiement', models.CharField(choices=[('payé', 'Payé'), ('en attente', 'En attente'), ('retard', 'Retard')], default='en attente', max_length=20)),
                ('type_cotisation', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], default='annuelle', max_length=20)),
                ('num_police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.police')),
            ],
        ),
        migrations.CreateModel(
            name='Recucontrole',
            fields=[
                ('idrec', models.AutoField(primary_key=True, serialize=False)),
                ('date_rec', models.DateField()),
                ('num_rec', models.CharField(max_length=20)),
                ('mtt_droit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_pv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_carte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_tht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtt_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idcont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controle')),
            ],
        ),
        migrations.CreateModel(
            name='DetailReparation',
            fields=[
                ('iddetail', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.piece')),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('idsin', models.AutoField(primary_key=True, serialize=False)),
                ('date_sinistre', models.DateField()),
                ('description', models.TextField()),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.police')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('idveh', models.AutoField(primary_key=True, serialize=False)),
                ('num_imm', models.CharField(max_length=10)),
                ('num_serie', models.CharField(max_length=20)),
                ('num_moteur', models.CharField(max_length=20)),
                ('puissance', models.IntegerField()),
                ('places', models.IntegerField()),
                ('poids_ch', models.IntegerField()),
                ('poids_vide', models.IntegerField()),
                ('date_circulation', models.DateField()),
                ('date_immatriculation', models.DateField()),
                ('date_emission', models.DateField()),
                ('annee', models.IntegerField()),
                ('charge_utile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(max_length=20)),
                ('cylindre', models.CharField(max_length=40)),
                ('image', models.TextField(blank=True, null=True)),
                ('idcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carosserie')),
                ('idcarb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carburant')),
                ('idcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categorie')),
                ('idmar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('idmod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modele')),
                ('idpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('idtraj', models.AutoField(primary_key=True, serialize=False)),
                ('date_sortie', models.DateField()),
                ('date_arriver', models.DateField(default=datetime.date.today)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('point_depart', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('kilometrage_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometrage_arrivee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('distance_cumulative', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('idveh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='api.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='reparation',
            name='idveh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule'),
        ),
        migrations.CreateModel(
            name='Ravitailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ravitaillement', models.DateField()),
                ('qtte_litre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idcarb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carburant')),
                ('idstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationservice')),
                ('idveh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='police',
            name='idveh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule'),
        ),
        migrations.AddField(
            model_name='controle',
            name='idveh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule'),
        ),
        migrations.CreateModel(
            name='vidange',
            fields=[
                ('idvid', models.AutoField(primary_key=True, serialize=False)),
                ('date_vidange', models.DateField()),
                ('type_huile', models.CharField(max_length=50)),
                ('qtte_huile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_u_vidange', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idveh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicule')),
            ],
        ),
    ]
